### ISSUE TITLE
is it possible to use on GPU device?

### ISSUE THREAD

**Issue by Yongtae723** [kajyuuen/daaja#31]
Hi!

thank you for the great library.
when I train with this augmentation, this takes so much more time than forward and backward process.

therefore, can we possibly use this augmentation on GPU to save time?

thank you

**Comment by kajyuuen** [comment]
Thanks for the good issue.

`BackTranslationAugmentor` is able to use on GPU.
I have not yet considered running other Augmentors on GPUs.

I'm considering multi-process support as another acceleration method apart from GPUs, but is that not enough?

**Comment by Yongtae723** [comment]
thank you for your kind reply!

to be honest, I have no idea whether your suggestion is enough or not.
cloud you tell me how much this process is faster than the original?

Best

**Comment by kajyuuen** [comment]
It doesn't seem very practical to run EDA on a GPU.
To ensure training performance and speed up the training process, it is recommended to perform data augmentation before training, not at the same time.
