### ISSUE TITLE
from daaja.methods.eda.easy_data_augmentor import EasyDataAugmentorにてエラー

### ISSUE THREAD

**Issue by naoki1213mj** [kajyuuen/daaja#32]
daajaをpipインストール後、`from daaja.methods.eda.easy_data_augmentor import EasyDataAugmentor`を行うと、
以下のエラーとなる。
`ConnectionError: HTTPConnectionPool(host='compling.hss.ntu.edu.sg', port=80): Max retries exceeded with url: /wnja/data/1.1/wnjpn.db.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b6a6cced0>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by kajyuuen** [comment]
現在、日本語WordNetがリンク切れしているのが原因のようです。
https://github.com/kajyuuen/daaja/blob/271d1c3bfef8608f96f51712c1bd0b61f12adf1f/daaja/resouces.py#L19
http://compling.hss.ntu.edu.sg/wnja/data/1.1/wnjpn.db.gz

WordNetを所有している場合、`wnjpn.db.gz`を`"/tmp/eda_ja/`以下に保存することで、一時しのぎ的な解決は可能です

**Comment by kajyuuen** [comment]
根本的な解決方法としては日本語WordNetの再配布を待つしか無いかと思われます。

**Comment by naoki1213mj** [comment]
ありがとうございます。wnjpn.db.gzを"/tmp/eda_ja/以下に保存した場合、`from daaja.methods.eda.easy_data_augmentor import EasyDataAugmentor`を実行すればよいのでしょうか。

**Comment by kajyuuen** [comment]
その通りです。
`/tmp/eda_ja/`は絶対パスを表しています・

**Comment by kajyuuen** [comment]
@naoki1213mj -san
v0.0.7にて、このエラーを修正したのでお知らせします。
